#### Environment for test SPRING_PROFILES_ACTIVE=test ####

dbUrl: jdbc:mariadb://localhost:3306/cloud_platform_db
dbUsername: root
dbPassword: gcsvn123

hpi:
  ## Tenant datsource: JDBC connection pool ##
  tenant-ds:
    tomcat:
      initial-size: 5
      max-active: 5
      max-wait: 10000
      min-idle: 1
      max-idle: 5

image.url.prefix: http://172.18.15.158:8080/media/api/v1/img
video.url.prefix: http://172.18.15.158:8080/media/api/v1/vod

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.uri:http://localhost:8761}/eureka/
  ## instance info changes when deploying on Tomcat
  instance:
    non-secure-port: 8080
    status-page-url: http://${eureka.hostname}:8080/media/info
    health-check-url: http://${eureka.hostname}:8080/media/health
    home-page-url: http://${eureka.hostname}:8080/media